# Generated by Django 3.1.7 on 2021-03-12 02:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='items')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200000.0)])),
                ('owns', models.BooleanField(default=True)),
                ('closet_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='holygrailapi.closet')),
            ],
        ),
        migrations.CreateModel(
            name='HolygrailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photos', models.ImageField(null=True, upload_to='pieceUsers')),
                ('bio', models.CharField(default='', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='closet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holygrailuser', to='holygrailapi.holygrailuser'),
        ),
    ]
