# Generated by Django 3.1.7 on 2021-03-15 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holygrailapi', '0002_auto_20210314_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
