# Generated by Django 3.1.7 on 2021-03-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holygrailapi', '0003_closet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='closet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holygrailapi.closet'),
        ),
    ]
