# Generated by Django 3.1.7 on 2021-03-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holygrailapi', '0005_closetproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='closet_id',
        ),
    ]
